kpurganaaAdmin/Controllers/AccesoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace kpurganaaAdmin.Controllers
{
    public class AccesoController : Controller
    {
        // GET: Acceso
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CambiarClave()
        {
            return View();
        }


        public ActionResult Reestablecer()
        {
            return View();
        }
    }
}

kpurganaaAdmin/Controllers/HomeController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Security.AccessControl;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using CapaEntidad;
using CapaNegocio;
using Microsoft.Ajax.Utilities;
namespace kpurganaaAdmin.Controllers

{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Usuarios()
        {
            return View();
        }
        [HttpGet]
        public JsonResult listarUsuarios()
        {
            List<Usuario> oLista = new List<Usuario>();


            oLista = new CN_Usuarios().listar();

            return Json( new { data = oLista} , JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult GuardarUsuario(Usuario objeto) {
            object resultado;
            string mensaje = string.Empty;

            if (objeto.IdUsuario == 0) {
                resultado = new CN_Usuarios().Registrar(objeto, out mensaje); 

            } else {
                resultado = new CN_Usuarios().Editar(objeto, out mensaje);
            }

            return Json(new { resultado = resultado, mensaje = mensaje}, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarUsuario(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Usuarios().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);


        }


        [HttpGet]
        public JsonResult VistaDashBoard()
        {
            DashBoard objeto = new CN_Reporte().verDashboard();

            return Json(new { resultado = objeto }, JsonRequestBehavior.AllowGet);
        }



    }
}

kpurganaaAdmin/Controllers/MantenedorController.cs
using CapaEntidad;
using CapaNegocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Newtonsoft.Json;
using System.Globalization;
using System.Configuration;
using System.IO;
using Newtonsoft.Json.Linq;
namespace kpurganaaAdmin.Controllers
{
    public class MantenedorController : Controller
    {
        // GET: Mantenerdor
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Habitaciones()
        {
            return View();
        }

        public ActionResult TipoHabitacion()
        {
            return View();
        }

        [HttpGet]
        public JsonResult ListarTipoHabitacion()
        {
            List<Tipohabitacion> oLista = new List<Tipohabitacion>();


            oLista = new CN_TipoHabitacion().listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarTipoHabitacion(Tipohabitacion objeto)
        {
            object resultado;
            string mensaje = string.Empty;

            if (objeto.IdTipoHabitacion == 0)
            {
                resultado = new CN_TipoHabitacion().Registrar(objeto, out mensaje);

            }
            else
            {
                resultado = new CN_TipoHabitacion().Editar(objeto, out mensaje);
            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult EliminarTipoHabitacion(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_TipoHabitacion().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);


        }

       
        public JsonResult ListarHabitacion()
        {
            List<Habitacion> oLista = new List<Habitacion>();


            oLista = new CN_Habitacion().listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarHabitacion(string objeto, HttpPostedFileBase archivoImagen)
        {
            
            string mensaje = string.Empty;
            bool operacion_Exitosa = true;
            bool guardar_imagen_Exito = true;

            Habitacion oHabitacion = new Habitacion();
            oHabitacion = JsonConvert.DeserializeObject<Habitacion>(objeto);

            decimal precio;
            if (decimal.TryParse(oHabitacion.PrecioTexto, NumberStyles.AllowDecimalPoint, new CultureInfo("es-CO"), out precio))
            {
                oHabitacion.Precio = precio;
            }
            else
            {

                return Json(new { operacionExitosa = false, mensaje = "El formato del precio debe ser ##.##" }, JsonRequestBehavior.AllowGet);

            }
            
            if (oHabitacion.IdHabitacion == 0)
            {
                //oHabitacion.IdTipoHabitacion = oHabitacion.TipoHabitacion.IdTipoHabitacion;
                int idHabitacionGenerado = new CN_Habitacion().Registrar(oHabitacion, out mensaje);
                if (idHabitacionGenerado != 0)
                {
                    oHabitacion.IdHabitacion = idHabitacionGenerado;
                }
                else
                {
                    operacion_Exitosa = false;
                }
            } else {
                operacion_Exitosa = new CN_Habitacion().Editar(oHabitacion, out mensaje);
            }

            if (operacion_Exitosa) {
                if (archivoImagen != null) {

                    string ruta_guardar = ConfigurationManager.AppSettings["ServidorFotos"];
                    string extension = Path.GetExtension(archivoImagen.FileName);
                    string nombre_imagen = string.Concat(oHabitacion.IdHabitacion.ToString(), extension);


                    try
                    {

                        archivoImagen.SaveAs(Path.Combine(ruta_guardar, nombre_imagen));
                    }
                    catch (Exception ex)
                    {

                       
                        guardar_imagen_Exito = false;
                        string msg = ex.Message;
                    }


                    if (guardar_imagen_Exito)
                    {
                        oHabitacion.RutaImagen = ruta_guardar;
                        oHabitacion.NombreImagen = nombre_imagen;
                        bool rspta = new CN_Habitacion().GuardarDatosImagen(oHabitacion, out mensaje);

                    }
                    else
                    {

                        mensaje = "Se guardo el producto pero hubo problemas con la imagen";
                    }
                }


                //return Json(new { operacionExitosa = operacion_Exitosa, idGenerado = oHabitacion, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
            }


            return Json(new { operacionExitosa = operacion_Exitosa, idGenerado = oHabitacion, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }


        [HttpPost]

        public JsonResult ImagenHabitacion(int id)
        {

            bool conversion;
            Habitacion oHabitacion = new CN_Habitacion().listar().Where(H => H.IdHabitacion == id).FirstOrDefault();
            string textoBase64 = CN_Recursos.ConvertirBase64(Path.Combine(oHabitacion.RutaImagen, oHabitacion.NombreImagen), out conversion);

            return Json(new
            {
                conversion = conversion,
                textoBase64 = textoBase64,
                Extension = Path.GetExtension(oHabitacion.NombreImagen)


            },
            JsonRequestBehavior.AllowGet
            );




            
        }


        [HttpPost]

        public JsonResult EliminarHabitacion(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Habitacion().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);


        }


    }

}

kpurganaaAdmin/Views/Acceso/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<
<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                                <div class="card-body">
                                    <form>
                                        <div class="form-floating mb-3">
                                            <input class="form-control" id="inputEmail" type="email" placeholder="name@example.com" />
                                            <label for="inputEmail">Email address</label>
                                        </div>
                                        <div class="form-floating mb-3">
                                            <input class="form-control" id="inputPassword" type="password" placeholder="Password" />
                                            <label for="inputPassword">Password</label>
                                        </div>
                                        <div class="form-check mb-3">
                                            <input class="form-check-input" id="inputRememberPassword" type="checkbox" value="" />
                                            <label class="form-check-label" for="inputRememberPassword">Remember Password</label>
                                        </div>
                                        <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                            <a class="small" href="password.html">Forgot Password?</a>
                                            <a class="btn btn-primary" href="index.html">Login</a>
                                        </div>
                                    </form>
                                </div>
                                <div class="card-footer text-center py-3">
                                    <div class="small"><a href="register.html">Need an account? Sign up!</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="js/scripts.js"></script>
</body>

</html>

kpurganaaAdmin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";

}


<h1 class="mt-4">Dashboard</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Dashboard</li>
</ol>


<div class="row">
    <div class="col-xl-3 col-md-6">
        <div class="card bg-success text-white mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-9">
                        <h6>Cantidad Clientes</h6>
                        <h6 id="totalcliente">0</h6>
                    </div>
                    <div class="col-sm-9">
                        <i class="fas fa-user fa-2x"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-warning text-white mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-9">
                        <h6>Cantidad Ventas</h6>
                        <h6 id="totalventa">0</h6>
                    </div>
                    <div class="col-sm-9">
                        <i class="fas fa-shopping-bag fa-2x"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-secondary text-white mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-9">
                        <h6>Cantidad Habitacioens</h6>
                        <h6 id="totalhabitacion">0</h6>
                    </div>
                    <div class="col-sm-9">
                        <i class="fas fa-box fa-2x"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-tags me-1"></i>
        Historial de venta
    </div>
    <div class="card-body">
        <form>

            <div class="row align-items-end">
                <div class="col-sm-2">
                    <div class="mb-2">
                        <label class="form-label"> Fecha Inicio:</label>
                        <input class="form-control" type="text" id="txtfechainicio" name="fechainicio" />
                    </div>

                </div>
                <div class="col-sm-2">
                    <div class="mb-2">
                        <label class="form-label"> Fecha Fin:</label>
                        <input class="form-control" type="text" id="txtfechafin" name="fechafin" />
                    </div>

                </div>


                <div class="col-sm-2">
                    <div class="d-grid mb-2">
                        <button class="btn btn-primary" id="btnbuscar" type="button"> <i class="fas fa-search"></i>Buscar</button>
                    </div>

                </div>

                <div class="col-sm-2">
                    <div class="d-grid mb-2">
                        <button class="btn btn-success" type="submit"> <i class="fas fa-file-excel"></i>Exportar</button>
                    </div>

                </div>


            </div>


        </form>
        <hr />

<div class="row">

        <div class="col-sm-12">
            <table id="tabla" class="display cell-border" style="width:100%">
                <thead>

                    <tr>

                        <td>Fecha Venta</td>
                        <td>Cliente</td>
                        <td>Precio</td>
                        <td>Cantidad</td>
                        <td>Total</td>


                    </tr>

                </thead>

                <tbody>
                </tbody>

            </table>
        </div>


    </div>


    </div>
</div>


@section scripts {
    <script>

        jQuery.ajax({
            url: '@Url.Action("VistaDashBoard", "Home")',
            type: "GET",
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function (data) {

                var objeto = data.resultado;

                $("#totalcliente").text(objeto.TotalCliente)
                $("#totalventa").text(objeto.TotalVenta)
                $("#totalhabitacion").text(objeto.TotalHabitacion)


            }



        });



    </script>

 }

kpurganaaAdmin/Views/Mantenedor/TipoHabitacion.cshtml
@{
    ViewBag.Title = "TipoHabitacion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{
    ViewBag.Title = "Usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Mantenimiento</a></li>
    <li class="breadcrumb-item active">TipoHabitacion</li>
</ol>


<div class="card">
    <div class="card-header">
        <i class="fas fa-users me-1"></i> List de Tipo de habitaciones
    </div>
    <div class="card-body">
        <div class="row">
            <div class=" col-12">

                <button type="button" class="btn btn-success" onclick="abrirModal(null)">Crear Nuevo Tipo de Habitacion</button>

            </div>

            
        </div>
        <hr />

        <table id="tabla" class="display cell-border" style=" width: 100%">
            <thead>
                <tr>
                    <th>Descripcion</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>


    </div>
</div>


<div class="modal fade" id="FormModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Tipo de Habitaciones</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body ">


                <input id="txtid" type="hidden" value="0" />

                <div class="row g-1">
                    <div class="col-sm-6">
                        <label for="txtdescripcion">Descripcion</label>
                        <input type="text" class="form-control" id="txtdescripcion" autocomplete="off">
                    </div>

                    <div class="col-sm-6">
                        <label for="cboactivo" class="form-label">Activo</label>
                        <select id="cboactivo" class="form-select">
                            <option value="1">Si</option>
                            <option value="0">No</option>
                        </select>
                    </div>


                </div>

                <div class="row mt-2">
                    <div class="col-12">

                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            A simple danger alert—check it out!
                        </div>


                    </div>
                </div>




            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>
@section scripts {
    <script>

        var tabladata;
        var filaSeleccionada;

        tabladata = $('#tabla').DataTable({
            responsive: true,
            ordering: false,

            "ajax": {

                 url: '@Url.Action("ListarTipoHabitacion", "Mantenedor")',
                 type: "GET",
                 dataType: "json",
            },

            "columns": [
                
                { "data": 'Descripcion' },
                {
                    "data": 'Activo', 'render': function (valor) {
                        console.log("VALOR ", valor)
                        if (valor) {

                            return '<span class="badge bg-success">Si</span>'
                        } else {
                            return '<span class="badge bg-danger">No</span>'
                        }



                    }

                },
                {
                    "defaultContent": '<button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fas fa-pen me-1"></i></button>' +
                        '<button type="button" class="btn btn-danger btn-sm  ms-2 btn-eliminar"><i class="fas fa-trash me-1"></i></button>',
                    "orderable": false,
                    "searchable": false,
                    "width": "90px"

                }

            ],
            "language": {
                "url": "https://datatables.net/plug-ins/i18n/Spanish"
            }
        });




        function abrirModal(json) {

            $("#txtid").val(0);
            $("#txtdescripcion").val("");
            $("#cboactivo").val(1);

            $("#mensajeError").hide();




            if (json != null) {

                $("#txtid").val(json.IdTipoHabitacion);
                $("#txtdescripcion").val(json.Descripcion);
                $("#cboactivo").val(json.Activo == true ? 1: 0);
            }

           $("#FormModal").modal("show");
        }

        $("#tabla tbody").on("click", ".btn-editar", function () {
             filaSeleccionada = $(this).closest("tr");
            var data = tabladata.row(filaSeleccionada).data();

            abrirModal(data);
        });



        $("#tabla tbody").on("click", ".btn-eliminar", function () {
            var tipohabitacionleccionado = $(this).closest("tr");
            var data = tabladata.row(tipohabitacionleccionado).data();

            swal({

                title: "Esta Seguro",
                text: "¿ Desea eliminar el Tipo de Habitacion ?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfim: true

            },

                function () {

                    jQuery.ajax({
                        url: '@Url.Action("EliminarTipoHabitacion", "Mantenedor")',
                        type: "POST",
                        data: JSON.stringify({ id: data.IdTipoHabitacion }),
                        dataType: "Json",
                        contentType: "application/json",
                        success: function (data) {

                            if (data.resultado) {
                                tabladata.row(tipohabitacionleccionado).remove().draw();

                            } else {


                                swal("No se pudo eliminar", data.mensaje, "error")
                            }

                        },
                        error: function (error) {

                            console.log(error)
                        },


                    });



                });


            console.log(data);


        })


        function Guardar() {
            var TipoHabitacion = {
                IdTipoHabitacion: $("#txtid").val(),
                Descripcion: $("#txtdescripcion").val(),
                 Activo: $("#cboactivo").val() == 1 ? true : false,
            }
          

            jQuery.ajax({
                url: '@Url.Action("GuardarTipoHabitacion", "Mantenedor")',
                type: "POST",
                data: JSON.stringify({ objeto: TipoHabitacion }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {



                    $(".modal-body").LoadingOverlay("hide")



                    //Categoria NUEVO
                    if (TipoHabitacion.IdTipoHabitacion == 0) {
                        if (data.resultado != 0) {

                            TipoHabitacion.IdTipoHabitacion = data.resultado;
                            tabladata.row.add(TipoHabitacion).draw(false);
                            $("#FormModal").modal("hide");
                        } else {

                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }


                        // categoria EDITAR
                    } else {

                        if (data.resultado) {

                            tabladata.row(filaSeleccionada).data(TipoHabitacion).draw(false);
                            filaSeleccionada = null;
                            $("#FormModal").modal("hide");
                        } else {



                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();

                        }



                    }

                },
                eror: function (error) {
                    $(".modal-body").LoadingOverlay("hide")

                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();
                },
                beforeSend: function () {

                    $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactor: 2,
                        text: "Cargando...",
                        size: 14

                    })

                }


            });




            //$("#FormModal").modal("show");
        }


    </script>
}

kpurganaaAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Kpurganaa</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        @*<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>*@
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Correo del Usuario</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Cerrar Sesion</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Rsumen</div>
                        <a class="nav-link" href="@Url.Action("Index", "Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <a class="nav-link" href="@Url.Action("Usuarios", "Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Usuarios
                        </a>
                        <div class="sb-sidenav-menu-heading">Mantenimiento</div>
                        <a class="nav-link" href="@Url.Action("Habitaciones", "Mantenedor")">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Habitaciones
                        </a>
                        <a class="nav-link" href="@Url.Action("TipoHabitacion","Mantenedor")">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            TipoHabitacion
                        </a>
                        @*<a class="nav-link" href="tables.html">
            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
            Tables
        </a>*@
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>







    @*@RenderBody()*@

    @*<li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("PaginaPrueba", "paginaTest", "Home", new { area = "" }, new { @class = "nav-link" })</li>*@





    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>